### ISSUE TITLE
How come `require` is included in the `params` by default?

### ISSUE THREAD

**Issue by TooTallNate** [sidorares/browserify-jade#10]
It's making the webpack builder complain since `require` is used as a variable instead of as a function.

```
WARNING in ./~/editor/lib/block-embed/embed-block.js
Critical dependencies:
2:64-71 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/editor/lib/block-embed/embed-block.js 2:64-71
```

https://github.com/sidorares/browserify-jade/blob/936f3441457c6590c69c82e9840372eb4b8bce1f/index.js#L10

Can we remove this part? I virtually never need `require` in my jade templates; instead I pass all the necessary dependencies in as locals.

**Comment by sidorares** [comment]
can't remember why it's there :(
Yes, I'm ok to remove whole `module.exports=function(params) { if (params) {params.require = require;}` line
